INSERT INTO GENRES (CODE, DESCRIPTION) VALUES ('ROCK', 'Rock');
INSERT INTO GENRES (CODE, DESCRIPTION) VALUES ('POP', 'Pop');
INSERT INTO GENRES (CODE, DESCRIPTION) VALUES ('JAZZ', 'Jazz');

INSERT INTO SURVEYS (EMAIL, GENRE_ID) VALUES ('test@test.com', 1);
INSERT INTO SURVEYS (EMAIL, GENRE_ID) VALUES ('test2@test.com', 2);
INSERT INTO SURVEYS (EMAIL, GENRE_ID) VALUES ('test3@test.com', 3);
INSERT INTO SURVEYS (EMAIL, GENRE_ID) VALUES ('test4@test.com', 3);